config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'

  resources :artists, only: %i[index new create]
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :songs
  has_one_attached :photo

  validates :title, :year, presence: true
  validates :year, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs
  has_one_attached :photo

  validates :name, :country, :artist_type, presence: true
  validates :name, uniqueness: true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  before_save :set_decade
  after_save :update_artist_points

  validates :title, :genre, :year, :album, presence: true
  validates :title, uniqueness: { scope: :artist_id }
  validates :year, numericality: { only_integer: true, greater_than_or_equal_to: 1000, less_than_or_equal_to: 3000 }

  private

  def set_decade
    self.decade = year - (year % 10)
  end

  def update_artist_points
    artist.update(points: artist.points + 21 - pos20.to_i) if artist.present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :photo)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password)
    end
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all.includes(photo_attachment: :blob)
  end

  def show
  end

  def new
    @artist = Artist.new
  end

  def create
    artist = Artist.new(params.require(:artist).permit(:name, :country, :artist_type, :photo))

    if artist.save
      flash.keep[:success] = 'Artist added successfully'
    else
      flash.now[:error] = 'Error: Artist could not be added'
    end
    redirect_to artists_path
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/artists/create.html.erb
<h1>Artists#create</h1>
<p>Find me in app/views/artists/create.html.erb</p>

app/views/artists/destroy.html.erb
<h1>Artists#destroy</h1>
<p>Find me in app/views/artists/destroy.html.erb</p>

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<%= stylesheet_link_tag('artist_index') %>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <%= value %>
  </div>
<% end %>

<h1>Artists</h1>

<div>
  <p>NAME - COUNTRY - TYPE - POINTS</p>
  <% @artists.each do |artist| %>
    <% if artist.photo.attached? %>
      <div>
        <%= image_tag artist.photo %>
      </div>
    <% end %>
    <div>
      <p><%= artist.name %> - <%= artist.country %> - <%= artist.artist_type %> - <%= artist.points %></p>
    </div>
  <% end %>
</div>

<div>
  <%= link_to new_artist_path do %>
    <button>
      <p>CREATE NEW ARTIST</p>
    </button>
  <% end %>
</div>

app/views/artists/new.html.erb
<div>
  <h2>CREATE A NEW ARTIST</h2>
</div>

<%= form_with model: @artist, url: artists_path, method: :post do |form| %>
  <div>
    <%= form.text_field :name, placeholder: "Name" %>
  </div>
  <div>
    <%= form.text_field :country, placeholder: "Country" %>
  </div>
  <div>
    <%= form.text_field :artist_type, placeholder: "Type" %>
  </div>
  <div>
    <%= form.label :photo, "Artist Image" %>
    <%= form.file_field :photo, placeholder: "Image Name" %>
  </div>

  <div>
    <div>
      <%= form.submit "SAVE ARTIST" %>
    </div>
    <%= link_to artists_path do %>
      <button>
        <p>ARTISTS PAGE</p>
      </button>
    <% end %>
  </div>
<% end %>

app/views/artists/show.html.erb
<h1>Artists#show</h1>
<p>Find me in app/views/artists/show.html.erb</p>

app/views/artists/update.html.erb
<h1>Artists#update</h1>
<p>Find me in app/views/artists/update.html.erb</p>

app/views/home/index.html.erb
<h1>Welcome to HP Audio</h1>
<p>This is a site where you can find the favorite artists and songs of this HP guy who is a great fun</p>
<%= link_to "Artists", artists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HPAudio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>